config/routes.rb
Reputacao::Application.routes.draw do
  resources :qualificacoes

  match ':controller(/:action(/:id))(.:format)'
  match 'inicio', controller: 'proprietarios', action: 'index'
  match 'categorias/:nome', controller: 'categorias', action: 'show'
  match 'rack',
	:to => proc{|env| [200, {"Content-Type" => "text/html"}, ["App Rack numa rota Rails"]]}
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clientes_controller.rb
# encoding: utf-8
class ClientesController < ApplicationController
	respond_to :html, :js
	
	def index
		@clientes = Cliente.order("nome")
		respond_with @cliente
	end
	
	def show
		@cliente = Cliente.find(params[:id])
		respond_with @cliente
	end
	
	def new
		@cliente = Cliente.new
		respond_with @cliente
	end
	
	def create
		@cliente = Cliente.new(params[:cliente])
		if @cliente.save
			redirect_to(action: "show", id: @cliente)
		else 
			render action: "new"
		end
	end
	
	def edit
		@cliente = Cliente.find(params[:id])
	end
	
	def update
		#recebe o id
		@cliente = Cliente.find(params[:id])
		if @cliente.update_attributes(params[:cliente])
			redirect_to(action: "show", id: @cliente)
		else
			render action: "edit"
		end
	end
	
	def destroy
		#recebe o id
		@cliente = Cliente.find(params[:id])
		#deleta o cliente pelo id recebido
		@cliente.destroy
		respond_with @cliente
		#retorna para a index
		redirect_to(action: "index")
	end
end

app/controllers/proprietarios_controller.rb
# encoding: utf-8
class ProprietariosController < ApplicationController
	respond_to :html, :js 

	def index
		@proprietarios = Proprietario.order("nome")
		respond_with @proprietario
	end
	
	def show
		@proprietario = Proprietario.find(params[:id])
		respond_with @proprietario
	end
	
	def new
		@proprietario = Proprietario.new
		respond_with @proprietario
	end
	
	def create
		@proprietario = Proprietario.new(params[:proprietario])
		if @proprietario.save
			redirect_to(action: "show", id: @proprietario)
		else 
			render action: "new"
		end
	end
	
	def edit
		@proprietario = Proprietario.find(params[:id])
	end
	
	def update
		#recebe o id
		@proprietario = Proprietario.find(params[:id])
		if @proprietario.update_attributes(params[:proprietario])
			redirect_to(action: "show", id: @proprietario)
		else
			render action: "edit"
		end
	end
	
	def destroy
		#recebe o id
		@proprietario = Proprietario.find(params[:id])
		#deleta o proprietario pelo id recebido
		@proprietario.destroy
		respond_with @proprietario
		#retorna para a index
		redirect_to(action: "index")
	end
end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qualificacoes }
    end
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.json
  def new
    @qualificacao = Qualificacao.new
	if params[:cliente]
		@qualificacao.cliente = Cliente.find(params[:cliente])
	end
	if params[:proprietario]
		@qualificacao.proprietario = Proprietario.find(params[:proprietario])
	end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao recebida com sucesso.' }
        format.json { render json: @qualificacao, status: :created, location: @qualificacao }
      else
        format.html { render action: "new" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to @qualificacao, notice: 'Qualificacao atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to qualificacoes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def menu_principal
		menu = %w(cliente qualificacao proprietario)
		menu_principal = "|"
		menu.each do |item|
		menu_principal << "|"
		menu_principal << link_to(item, :controller => item.pluralize)
		menu_principal << "|"
		end
	menu_principal << "|"
	raw menu_principal
	end

end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/helpers/proprietarios_helper.rb
module ProprietariosHelper
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/clientes/_form.html.erb
<%= form_for :cliente, url: {action: 'create'} do |f| %>
<% if @cliente.errors.any? %>
	<ul>
		<% @cliente.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
<% end %>
<div class="field">
	<%= f.label :nome%>
	<%= f.text_field :nome %><br/>
</div>
<div class="field">
	<%= f.label :idade%>
	<%= f.text_field :idade %><br/>
</div>
<div class="actions">	
	<%= submit_tag 'Adicionar' %>
</div>
<% end %>
| <%= link_to 'Voltar', {action: 'index' } %> |

app/views/clientes/edit.html.erb
<h2>Editar Cliente</h2>
<% if @cliente.errors.any? %>
<ul>
	<% @cliente.errors.full_messages.each do |msg| %>
	<li>
		<%= msg %>
	</li>
<% end %>
</ul>
<% end %>
<%= form_for :cliente, url: {action: 'update', id: @cliente} do |f| %>
	<div class="field">
		<%= f.label :nome %>
		<%= f.text_field :nome %><br/>
	</div>
	<div class="field">
		<%= f.label :idade %>
		<%= f.text_field :idade %><br/>
	</div>
	<div class="actions">
		<%= submit_tag 'Atualizar' %>
	</div>
<% end %>
| <%= link_to 'Voltar', {action: 'index' } %> |

app/views/clientes/index.html.erb
<h2>Listar Clientes</h2>
<table class="table table-striped">
	<tr>
		<th>Nome</th>
		<th>Idade</th>
		<th></th>
	</tr>
<% @clientes.each do |cliente| %>
<tr>
	<td>
		<%= cliente.nome %>
	</td>
	<td>
		<%= cliente.idade %>
	</td>
	<td>
		<%= link_to 'Mostrar', action: 'show', id: cliente %> |
		<%= link_to 'Editar', action: 'edit', id: cliente %> 
	</td>
</tr>
<% end %>
</table>
<table>
	<tr>
		<td>
			<a href='clientes/new' class='btn btn-small pull-right'>Inserir Novo</a><br/>
		</td>
	</tr>
</table>

app/views/clientes/new.html.erb
<h2>Adicionar Cliente</h2>
<%= render 'form' %>

app/views/clientes/show.html.erb
<h2>Exibir Cliente</h2>
<table class="table table-striped">
	<tr>
		<th>Nome</th>
		<th>Idade</th>
		<th></th>
		
	</tr>
	<tr>	
		<td>
			<%= @cliente.nome %>
		</td>
		<td>
			<%= @cliente.idade %>
		</td>
		<td>
			| <%= link_to 'Editar', {action: 'edit', id: @cliente } %> |
		</td>
	</tr>
</table>

 | 
<%= link_to "Nova Qualificacao", :controller => "qualificacoes",
                                            :action => "new",
                                            :proprietario => @cliente %> | 


<%= link_to 'Voltar', {action: 'index' } %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Programa de verificacao de Reputacao</title>
	  <%= stylesheet_link_tag 'scaffold' %>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar">
				<div class="navbar-inner">
					<a class="brand" >Reputacao</a>
					<ul class="nav">
						<li class="divider-vertical"><a href="http://localhost:3000/proprietarios">Proprietarios</a></li>
						<li class="divider-vertical"><a href="http://localhost:3000/clientes">Clientes</a></li>
						<li class="divider-vertical"><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
					</ul>
				</div>
			</div>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/proprietarios/_form.html.erb
<%= form_for :proprietario, url: {action: 'create'} do |f| %>
	<% if @proprietario.errors.any? %>
	<ul>
		<% @proprietario.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
<% end %>
<div class="field">
	<%= f.label :nome%>
	<%= f.text_field :nome %><br/>
</div>
<div class="field">
	<%= f.label :nacionalidade%> 
	<%= f.text_field :nacionalidade %><br/>
</div>
<div class="actions">
	<%= submit_tag 'Adicionar' %>
</div>
<% end %>
| <%= link_to 'Voltar', {action: 'index' } %> |

app/views/proprietarios/_titulo.html.erb
<h1>Reputacao Proprietario</h1><br/>

app/views/proprietarios/edit.html.erb
<h2>Editar Proprietario</h2>
<% if @proprietario.errors.any? %>
	<ul>
		<% @proprietario.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
		<% end %>
	</ul>
<% end %>
<%= form_for :proprietario, url: {action: 'update', id: @proprietario} do |f| %>
	<div class="field">
		<%= f.label :nome %>
		<%= f.text_field :nome %><br/>
	</div>
	<div class="field">
		<%= f.label :nacionalidade %>
		<%= f.text_field :nacionalidade %><br/>
	</div>
	<div class="actions">
		<%= submit_tag 'Atualizar' %>
	</div>
<% end %>
| <%= link_to 'Voltar', {action: 'index' } %> |

app/views/proprietarios/index.html.erb
<h2>Listar Proprietarios</h2>
<table class="table table-striped">
	<tr>
		<th>Nome</th>
		<th>Nacionalidade</th>
		<th></th>
	</tr>
<% @proprietarios.each do |proprietario| %>
	<tr>	
		<td>
			<%= proprietario.nome %>
		</td>
		<td>
			<%= proprietario.nacionalidade %>
		</td>
		<td>
			<%= link_to 'Mostrar', action: 'show', id: proprietario %> | 
			<%= link_to 'Editar', action: 'edit', id: proprietario %> 
		</td>
	</tr>
<% end %>
</table>
<table>
	<tr>
		<td>
			<a href='/proprietarios/new' class='btn btn-small pull-right'>Inserir Novo</a><br/>
		</td>
	</tr>
</table>

app/views/proprietarios/new.html.erb
<h2>Adicionar Proprietario</h2>
<%= render 'form' %>

app/views/proprietarios/show.html.erb
<h2>Exibir Proprietario</h2>
<table class="table table-striped">
	<tr>
		<th>Nome</th>
		<th>Nacionalidade</th>
		<th></th>
		
	</tr>
	<tr>	
		<td>
			<%= @proprietario.nome %>
		</td>
		<td>
			<%= @proprietario.nacionalidade %>
		</td>
		<td>
			| <%= link_to 'Editar', {action: 'edit', id: @proprietario } %> |
		</td>
	</tr>


<!---
<p>
	<b>Nome: </b>
	<%= @proprietario.nome %>
</p>
<p>
	<b>Nacionalidade: </b>
	<%= @proprietario.nacionalidade %>
</p>
--->

</table>

 | 
<%= link_to "Qualificar este proprietario", :controller => "qualificacoes",
                                            :action => "new",
                                            :proprietario => @proprietario %> | 


<%= link_to 'Voltar', {action: 'index' } %> |

app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  	<!--- Exibindo no select os nomes dos clientes --->
	<% if @qualificacao.cliente %>
		<%= f.hidden_field 'cliente_id' %>
	<% else %>
		<p><%= f.label :cliente_id %>
		<%= f.collection_select(:cliente_id, Cliente.order('nome'), :id, :nome, {:prompt => true}) %></p>
    <% end %>
  </div>
  <div class="field">
	<!--- Exibindo no select os nomes dos propretarios --->
	<% if @qualificacao.proprietario %>
		<%= f.hidden_field 'proprietario_id' %>
	<% else %>
		<p><%= f.label :proprietario_id %>
		<%= f.collection_select(:proprietario_id, Proprietario.order('nome'), :id, :nome, {:prompt => true}) %></p>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :nota %>
    <%= f.text_field :nota %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h2>Editar qualificacao</h2>
<%= render 'form' %>
| <%= link_to 'Voltar', qualificacoes_path %> |

app/views/qualificacoes/index.html.erb
<h2>Listar Qualificacoes</h2>
<table class="table table-striped">
  <tr>
    <th>Cliente</th>
    <th>Proprietario</th>
    <th>Nota</th>
    <th></th>
    <th></th>
  </tr>

<% @qualificacoes.each do |qualificacao| %>
  <tr>
    <td><%= qualificacao.cliente.nome %></td>
    <td><%= qualificacao.proprietario.nome %></td>
    <td><%= qualificacao.nota %></td>
    <td>
		<%= link_to 'Mostrar', qualificacao %> |
		<%= link_to 'Editar', edit_qualificacao_path(qualificacao) %> | 
		<%= link_to 'Deletar', qualificacao, confirm: 'Confirma?', method: :delete %>
	</td> 
  </tr>
<% end %>
</table>
<table>
	<tr>
		<td>
			<a href='/qualificacoes/new' class='btn btn-small pull-right'>Inserir Qualificacao</a><br/>
		</td>
	</tr>
</table>

app/views/qualificacoes/new.html.erb
<h1>Nova qualificacao</h1>

<%= render 'form' %>

| <%= link_to 'Voltar', qualificacoes_path %> |

app/views/qualificacoes/show.html.erb
<h2>Exibir Qualificacao</h2>
<p id="notice"><%= notice %></p>
<table class="table table-striped">
	<tr>
		<th>Cliente</th>
		<th>Proprietario</th>
		<th>Nota</th>
		<th></th>
		
	</tr>
	<tr>	
		<td>
			<%= @qualificacao.cliente.nome %>
		</td>
		<td>
			<%= @qualificacao.proprietario.nome %>
		</td>
		<td>
			<%= @qualificacao.nota %>
		</td>
		<td>
			| <%= link_to 'Editar', edit_qualificacao_path(@qualificacao) %> |
		</td>
	</tr>
</table>

 | 
<%= link_to 'Voltar', qualificacoes_path %> |